{
  "version": "3",
  "services": {
    "nginx": {
      "image": "recipeyak/nginx:latest",
      "volumes": [
        "react-static-files:/var/app/dist",
        "django-static-files:/var/app/django/static"
      ],
      "logging": {
        "driver": "syslog",
        "options": {
          "syslog-address": "udp://logs.papertrailapp.com:50183",
          "tag": "{{.Name}}"
        }
      },
      "depends_on": [
        "django",
        "react"
      ],
      "ports": [
        "80:80"
      ]
    },
    "django": {
      "image": "recipeyak/django:latest",
      "volumes": [
        "django-static-files:/var/app/static-files"
      ],
      "logging": {
        "driver": "syslog",
        "options": {
          "syslog-address": "udp://logs.papertrailapp.com:50183",
          "tag": "{{.Name}}"
        }
      },
      "command": "sh bootstrap-prod.sh",
      "depends_on": [
        "db"
      ],
      "env_file": [
        ".env-production"
      ],
      "restart": "always"
    },
    "db": {
      "image": "postgres:10.1",
      "volumes": [
        "pgdata:/var/lib/postgresql/data"
      ],
      "logging": {
        "driver": "syslog",
        "options": {
          "syslog-address": "udp://logs.papertrailapp.com:50183",
          "tag": "{{.Name}}"
        }
      },
      "command": [
        "-c",
        "shared_preload_libraries=pg_stat_statements",
        "-c",
        "pg_stat_statements.max=10000",
        "-c",
        "pg_stat_statements.track=all"
      ],
      "ports": [
        "5432:5432"
      ]
    },
    "react": {
      "image": "recipeyak/react:latest",
      "volumes": [
        "react-static-files:/var/app/dist"
      ],
      "logging": {
        "driver": "syslog",
        "options": {
          "syslog-address": "udp://logs.papertrailapp.com:50183",
          "tag": "{{.Name}}"
        }
      },
      "command": "sh bootstrap.sh",
      "env_file": [
        ".env-production"
      ]
    }
  },
  "volumes": {
    "pgdata": {
      "driver": "local"
    },
    "django-static-files": {
      "driver": "local"
    },
    "react-static-files": {
      "driver": "local"
    }
  }
}