version: '3'
services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - react-static-files:/var/app/dist
      - django-static-files:/var/app/django/static
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "RecipeYak"
        tag: "{{.Name}}"
    depends_on:
      - django
      - react
  django:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    env_file:
      - .env
    command: sh bootstrap-prod.sh
    volumes:
      - django-static-files:/var/app/static-files
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "RecipeYak"
        tag: "{{.Name}}"
    depends_on:
     - db
  db:
    image: postgres:10.1-alpine
    ports:
      - "5432:5432"
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "RecipeYak"
        tag: "{{.Name}}"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
      args:
        - OAUTH_BITBUCKET_CLIENT_ID=${OAUTH_BITBUCKET_CLIENT_ID}
        - OAUTH_BITBUCKET_REDIRECT_URI=${OAUTH_BITBUCKET_REDIRECT_URI}
        - OAUTH_FACEBOOK_CLIENT_ID=${OAUTH_FACEBOOK_CLIENT_ID}
        - OAUTH_FACEBOOK_REDIRECT_URI=${OAUTH_FACEBOOK_REDIRECT_URI}
        - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
        - OAUTH_GITHUB_REDIRECT_URI=${OAUTH_GITHUB_REDIRECT_URI}
        - OAUTH_GITLAB_CLIENT_ID=${OAUTH_GITLAB_CLIENT_ID}
        - OAUTH_GITLAB_REDIRECT_URI=${OAUTH_GITLAB_REDIRECT_URI}
        - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
        - OAUTH_GOOGLE_REDIRECT_URI=${OAUTH_GOOGLE_REDIRECT_URI}
        - FRONTEND_SENTRY_DSN=${FRONTEND_SENTRY_DSN}
    command: sh bootstrap.sh
    env_file:
      - .env
    volumes:
      - react-static-files:/var/app/dist
    logging:
      driver: awslogs
      options:
        awslogs-group: "RecipeYak"
        tag: "{{.Name}}"
volumes:
  pgdata:
    driver: local
  django-static-files:
    driver: local
  react-static-files:
    driver: local
