version: '3'
services:
  nginx:
    image: recipeyak/nginx:latest
    ports:
      - "80:80"
    volumes:
      - react-static-files:/var/app/dist
      - django-static-files:/var/app/django/static
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs.papertrailapp.com:50183"
        tag: "{{.Name}}"
    depends_on:
      - django
      - react
  django:
    restart: always
    image: recipeyak/django:latest
    env_file:
      - .env-production
    command: sh bootstrap-prod.sh
    volumes:
      - django-static-files:/var/app/static-files
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs.papertrailapp.com:50183"
        tag: "{{.Name}}"
    depends_on:
     - postgres
  postgres:
    image: recipeyak/postgres:latest
    command: [
      "-c", 'shared_preload_libraries="pg_stat_statements"',
      "-c", "pg_stat_statements.max=10000",
      "-c", "pg_stat_statements.track=all",
    ]
    ports:
      - "5432:5432"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs.papertrailapp.com:50183"
        tag: "{{.Name}}"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  pgdump:
    image: recipeyak/pgdump:latest
    env_file:
      - .env-production
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs.papertrailapp.com:50183"
        tag: "{{.Name}}"
  react:
    image: recipeyak/react:latest
    command: sh bootstrap.sh
    env_file:
      - .env-production
    volumes:
      - react-static-files:/var/app/dist
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs.papertrailapp.com:50183"
        tag: "{{.Name}}"
volumes:
  pgdata:
    driver: local
  django-static-files:
    driver: local
  react-static-files:
    driver: local
