# this file enables building all our images with one command
# docker-compose -f docker-compose-prod.yml build
version: '3'
services:
  nginx:
    build: ./nginx/
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
      args:
        - OAUTH_BITBUCKET_CLIENT_ID=${OAUTH_BITBUCKET_CLIENT_ID}
        - OAUTH_BITBUCKET_REDIRECT_URI=${OAUTH_BITBUCKET_REDIRECT_URI}
        - OAUTH_FACEBOOK_CLIENT_ID=${OAUTH_FACEBOOK_CLIENT_ID}
        - OAUTH_FACEBOOK_REDIRECT_URI=${OAUTH_FACEBOOK_REDIRECT_URI}
        - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
        - OAUTH_GITHUB_REDIRECT_URI=${OAUTH_GITHUB_REDIRECT_URI}
        - OAUTH_GITLAB_CLIENT_ID=${OAUTH_GITLAB_CLIENT_ID}
        - OAUTH_GITLAB_REDIRECT_URI=${OAUTH_GITLAB_REDIRECT_URI}
        - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
        - OAUTH_GOOGLE_REDIRECT_URI=${OAUTH_GOOGLE_REDIRECT_URI}
        - FRONTEND_SENTRY_DSN=${FRONTEND_SENTRY_DSN}
