# see: https://docs.netlify.com/configure-builds/file-based-configuration/
[[redirects]]
  from = "/api/*"
  to = "https://recipeyak.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/avatar/*"
  to = "https://recipeyak.com/avatar/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
