# see: https://docs.netlify.com/configure-builds/file-based-configuration/
[[redirects]]
  from = "/api/*"
  to = "https://recipeyak.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/avatar/*"
  to = "https://recipeyak.com/avatar/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/recipes.json"
  to = "https://recipeyak.com/:splat.json"
  status = 200
  force = true

[[redirects]]
  from = "/recipes.yaml"
  to = "https://recipeyak.com/:splat.yaml"
  status = 200
  force = true

[[redirects]]
  from = "/recipes.yml"
  to = "https://recipeyak.com/:splat.yml"
  status = 200
  force = true

[[redirects]]
  from = "/recipes.ics"
  to = "https://recipeyak.com/:splat.ics"
  status = 200
  force = true

[[redirects]]
  from = "/recipes/:id.json"
  to = "https://recipeyak.com/:id.json"
  status = 200
  force = true

[[redirects]]
  from = "/recipes/:id.yaml"
  to = "https://recipeyak.com/:id.yaml"
  status = 200
  force = true

[[redirects]]
  from = "/recipes/:id.yml"
  to = "https://recipeyak.com/:id.yml"
  status = 200
  force = true

[[redirects]]
  from = "/recipes/:id.ics"
  to = "https://recipeyak.com/:id.ics"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
