# see: https://docs.netlify.com/configure-builds/file-based-configuration/
[[redirects]]
  from = "/api/*"
  to = "https://recipeyak.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/avatar/*"
  to = "https://recipeyak.com/avatar/:splat"
  status = 200
  force = true

[[redirects]]
  from = "*.json"
  to = "https://recipeyak.com/:splat.json"
  status = 200
  force = true

[[redirects]]
  from = "*.yaml"
  to = "https://recipeyak.com/:splat.yaml"
  status = 200
  force = true

[[redirects]]
  from = "*.yml"
  to = "https://recipeyak.com/:splat.yml"
  status = 200
  force = true

[[redirects]]
  from = "*.ics"
  to = "https://recipeyak.com/:splat.ics"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
