---
- hosts: recipeyak

  vars_prompt:
    - name: "maintenance_on"
      prompt: "Enable maintenance mode?"
      private: no

  tasks:
    - name: enable maintenance mode
      raw: docker container exec nginx touch maintenance_on
      when: maintenance_on | bool

    - name: disable maintenance mode
      raw: docker container exec nginx rm -f maintenance_on
      when: not (maintenance_on | bool)
