version: 2
jobs:
  test_python:
    docker:
      - image: circleci/python:3.6.1
        environment:
          DEBUG: 1
          DATABASE_URL: postgres://postgres@127.0.0.1:5432/postgres
          PIPENV_VENV_IN_PROJECT: 1
      - image: circleci/postgres:9.5-alpine

    steps:
      - checkout
      # https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - backend-v1-dependencies-cache-{{ checksum "backend/Pipfile.lock" }}
      - run:
          name: install dependencies
          working_directory: backend
          command: |
            sudo pip3 install pipenv
            make install
      - save_cache:
          paths:
            - ./backend/.venv
          key: backend-v1-dependencies-cache-{{ checksum "backend/Pipfile.lock" }}
      - run:
          name: run tests
          working_directory: backend
          command: |
            mkdir -p ~/backend/reports
            make ci
      - store_test_results:
          path: ~/backend/reports
  test_javascript:
    docker:
      - image: circleci/node:6.12.3
        environment:
          DEBUG: 1

    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-v1-dependencies-{{ checksum "frontend/package.json" }}
            - frontend-v1-dependencies-
      - run:
          name: install dependencies
          working_directory: frontend
          command: |
            npm install
      - save_cache:
          paths:
            - ./frontend/node_modules
          key: frontend-v1-dependencies-{{ checksum "frontend/package.json" }}
      - run:
          name: run tests
          working_directory: frontend
          command: npm run test-cov

  lint_javascript:
    docker:
      - image: circleci/node:6.12.3
        environment:
          DEBUG: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-v1-dependencies-{{ checksum "frontend/package.json" }}
            - frontend-v1-dependencies-
      - run:
          name: install dependencies
          working_directory: frontend
          command: |
            npm install
      - save_cache:
          paths:
            - ./frontend/node_modules
          key: frontend-v1-dependencies-{{ checksum "frontend/package.json" }}
      - run:
          name: run linter
          working_directory: frontend
          command: npm run lint
  build_javascript:
    docker:
      - image: circleci/node:6.12.3
        environment:
          DEBUG: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-v1-dependencies-{{ checksum "frontend/package.json" }}
            - frontend-v1-dependencies-
      - run:
          name: install dependencies
          working_directory: frontend
          command: |
            npm install
      - save_cache:
          paths:
            - ./frontend/node_modules
          key: frontend-v1-dependencies-{{ checksum "frontend/package.json" }}
      - run:
          name: run build
          working_directory: frontend
          command: npm run build
workflows:
  version: 2
  test:
    jobs:
      - test_python
      - test_javascript
      - lint_javascript
      - build_javascript
