version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          working_directory: backend
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./backend/venv
          key: v1-dependencies-{{ checksum "backend/requirements.txt" }}
      - run:
          name: run tests
          working_directory: backend
          command: |
            . venv/bin/activate
            mkdir reports
            pytest --cov-config .coveragerc --cov --junit-xml reports/output.xml
      - store_test_results:
          path: ~/backend/reports
