version: 2
jobs:
  test_python:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-v1--dependencies-{{ checksum "backend/requirements.txt" }}
            - backend-v1-dependencies-
      - run:
          name: install dependencies
          working_directory: backend
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./backend/venv
          key: backend-v1-dependencies-{{ checksum "backend/requirements.txt" }}
      - run:
          name: run tests
          working_directory: backend
          command: |
            . venv/bin/activate
            mkdir -p ~/backend/reports
            pytest --cov-config .coveragerc --cov --mypy --junit-xml ~/backend/reports/output.xml
      - store_test_results:
          path: ~/backend/reports
  test_javascript:
    docker:
      - image: circleci/node:6

    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-v1-dependencies-{{ checksum "frontend/package.json" }}
            - frontend-v1-dependencies-
      - run:
          name: install dependencies
          working_directory: frontend
          command: |
            npm install
      - save_cache:
          paths:
            - ./frontend/node_modules
          key: frontend-v1-dependencies-{{ checksum "frontend/package.json" }}
      - run:
          name: run tests
          working_directory: frontend
          command: npm run test-cov
workflows:
  version: 2
  test:
    jobs:
      - test_python
      - test_javascript
