version: 2

jobs:
  block_network_job:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: first command
          command: |
            echo "foo"
      - run:
          name: test
          command: |
            curl -I https://kodiakhq.com


workflows:
  version: 2
  test:
    jobs:
      - block_network_job
