name: Common

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# TODO: Skip if no changes in directory
jobs:
  docker_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Run linter
        uses: jbergstroem/hadolint-gh-action@83e551589b57fb5bc5ad415fbcde93da0d2641a1
        with:
          dockerfile: "**/*.Dockerfile"

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          sudo apt install shellcheck
      - name: Run shellcheck
        run: ./s/shellcheck
