name: Containers

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# TODO: Skip if no changes in directory
jobs:
  build_api_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        working-directory: "./backend"
        run: |
          git_sha=${{ github.event.pull_request.head.sha || github.sha }}
          docker build -f django.Dockerfile \
          --tag recipeyak/django:$git_sha \
          --build-arg GIT_SHA=$git_sha .
          docker push recipeyak/django:$git_sha
          echo "### Pushed recipeyak/django:$git_sha" >> $GITHUB_STEP_SUMMARY

  build_ui_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        working-directory: "./frontend"
        run: |
          git_sha=${{ github.event.pull_request.head.sha || github.sha }}
          docker build -f react.Dockerfile \
          --tag recipeyak/react:$git_sha \
          --build-arg GIT_SHA=$git_sha .
          docker push recipeyak/react:$git_sha
          echo "### Pushed recipeyak/react:$git_sha" >> $GITHUB_STEP_SUMMARY

  build_proxy_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        working-directory: "./infra/nginx"
        run: |
          git_sha=${{ github.event.pull_request.head.sha || github.sha }}
          docker build -f nginx.Dockerfile \
          --tag recipeyak/nginx:$git_sha \
          --build-arg GIT_SHA=$git_sha .
          docker push recipeyak/nginx:$git_sha
          echo "### Pushed recipeyak/nginx:$git_sha" >> $GITHUB_STEP_SUMMARY
