name: Frontend

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# TODO: Skip if no changes in directory
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./frontend/package.json"
          cache-dependency-path: "./frontend/yarn.lock"
          cache: "yarn"
      - name: Install dependencies
        working-directory: "frontend"
        run: yarn install --frozen-lockfile
      - name: Run tests
        working-directory: "frontend"
        run: ./s/test --no-watch --reporter junit --outputFile ~/test-results/frontend_tests.xml
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ~/test-results
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./frontend/package.json"
          cache-dependency-path: "./frontend/yarn.lock"
          cache: "yarn"
      - name: Install dependencies
        working-directory: "frontend"
        run: yarn install --frozen-lockfile
      - name: Run linter
        working-directory: "frontend"
        run: |
          ./s/lint
          ./s/build
      - name: Move artifacts
        working-directory: "frontend"
        run: |
          mkdir -p /tmp/frontend-artifacts
          cp -R stats.html /tmp/frontend-artifacts
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: frontend-artifacts
          path: /tmp/frontend-artifacts
