name: Infrastructure

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "SHA to deploy"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# TODO: Skip if no changes in directory
jobs:
  lint_docker:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Run linter
        uses: jbergstroem/hadolint-gh-action@83e551589b57fb5bc5ad415fbcde93da0d2641a1
        with:
          dockerfile: "**/*.Dockerfile"

  lint_shell:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          sudo apt install shellcheck
      - name: Run shellcheck
        run: ./s/shellcheck

  build_api_container:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        working-directory: "./backend"
        run: |
          git_sha=${{ github.event.pull_request.head.sha || github.sha }}
          docker build -f django.Dockerfile \
          --tag recipeyak/django:$git_sha \
          --build-arg GIT_SHA=$git_sha .
          docker push recipeyak/django:$git_sha
          echo "Pushed \`recipeyak/django:$git_sha\`" >> $GITHUB_STEP_SUMMARY

  build_ui_container:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        working-directory: "./frontend"
        run: |
          git_sha=${{ github.event.pull_request.head.sha || github.sha }}
          docker build -f react.Dockerfile \
          --tag recipeyak/react:$git_sha \
          --build-arg GIT_SHA=$git_sha .
          docker push recipeyak/react:$git_sha
          echo "Pushed \`recipeyak/react:$git_sha\`" >> $GITHUB_STEP_SUMMARY

  deploy:
    needs: [build_api_container, build_ui_container]
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
    steps:
      - uses: actions/checkout@v3
      # https://maxschmitt.me/posts/github-actions-ssh-key
      - name: "Install ssh key"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan $SSH_HOST >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/github_actions
      - env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git_sha=${{ github.event.pull_request.head.sha || github.sha }}
          ssh $SSH_USER@$SSH_HOST "./deploy $git_sha"
