name: UI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@c449d86cf33a2a6c7a4193264cc2578e2c3266d4 # pin@v4
        with:
          paths: '["frontend/**", ".github/workflows/**"]'
  test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/yarn.lock"
          cache: "yarn"
      - name: Install dependencies
        working-directory: "frontend"
        run: yarn install --frozen-lockfile
      - name: Run tests
        working-directory: "frontend"
        run: ./s/test --no-watch --reporter junit --outputFile ~/test-results/frontend_tests.xml
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ~/test-results
  lint:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/yarn.lock"
          cache: "yarn"
      - name: Install dependencies
        working-directory: "frontend"
        run: yarn install --frozen-lockfile
      - run: echo "::add-matcher::.github/problem-matcher-prettier.json"
      - name: Run linter
        working-directory: "frontend"
        run: |
          ./s/lint
          ./s/build
      - run: echo "::remove-matcher::.github/problem-matcher-prettier.json"
      - name: Move artifacts
        working-directory: "frontend"
        run: |
          mkdir -p /tmp/frontend-artifacts
          cp -R stats.html /tmp/frontend-artifacts
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: frontend-artifacts
          path: /tmp/frontend-artifacts
